apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "orderly-ape.fullname" . }}
  labels:
    {{- include "orderly-ape.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  {{- if .Values.persistence.enabled }}
  strategy:
    type: Recreate
  {{- end }}
  selector:
    matchLabels:
      {{- include "orderly-ape.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "orderly-ape.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "orderly-ape.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: {{ .Chart.Name }}-migrate
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - "sh"
            - "-c"
            - |
              ./manage.py migrate --noinput

              cat <<EOF | python ./manage.py shell
              import environ

              # Create the superuser
              from django.contrib.auth import get_user_model
              env = environ.FileAwareEnv()
              User = get_user_model()
              admin_user = env.str("ADMIN_USER", default="")
              admin_password = env.str("ADMIN_PASSWORD", default="")
              User.objects.filter(username=admin_user).exists() or \
                  User.objects.create_superuser(
                    admin_user,
                    f"{admin_user}@example.com",
                    admin_password,
                  )

              # Setup default test output
              from loatest.models import TestOutput

              influxdb_url = env.str("INFLUXDB_URL", default="http://localhost:8086")
              influxdb_token = env.str("INFLUXDB_TOKEN", default="")
              influxdb_org = env.str("INFLUXDB_ORG", default="default")
              influxdb_bucket = env.str("INFLUXDB_BUCKET", default="default")
              influxdb_tls_skip_verify = env.bool("INFLUXDB_TLS_SKIP_VERIFY", default=False)

              if influxdb_token and TestOutput.objects.count() == 0:
                  output = TestOutput.objects.get_or_create(name="default")
                  output.influxdb_url=influxdb_url
                  output.influxdb_token=influxdb_token
                  output.influxdb_org=influxdb_org
                  output.influxdb_bucket=influxdb_bucket
                  output.insecure_skip_verify=influxdb_tls_skip_verify
              EOF
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            {{- with .Values.env }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- if not ( include "orderly-ape.hasEnvVar" (list "ADMIN_PASSWORD" .) ) }}
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "orderly-ape.fullname" . }}
                  key: admin-password
            {{- end }}
            {{- if not ( include "orderly-ape.hasEnvVar" (list "ADMIN_USER" .) ) }}
            - name: ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "orderly-ape.fullname" . }}
                  key: admin-user
            {{- end }}
            {{- if not ( include "orderly-ape.hasEnvVar" (list "ALLOWED_HOSTS" .) ) }}
            - name: ALLOWED_HOSTS
              value: localhost,127.0.0.1,$(MY_POD_IP){{ if .Values.ingress.enabled }}{{ range .Values.ingress.hosts }}{{ print "," .host }}{{ end }}{{ end }}
            {{- end }}
            {{- if and .Values.ingress.enabled .Values.ingress.tls }}
            {{- if not ( include "orderly-ape.hasEnvVar" (list "CSRF_TRUSTED_ORIGINS" .) ) }}
            - name: CSRF_TRUSTED_ORIGINS
              value: http://127.0.0.1{{ range .Values.ingress.hosts }}{{ print ",https://" .host }}{{ end }}
            {{- end }}
            {{- end }}
            {{- if not ( include "orderly-ape.hasEnvVar" (list "DATABASE_URL" .) ) }}
            - name: DATABASE_URL
              value: "sqlite:////data/db.sqlite3"
            {{- end }}
          volumeMounts:
            - mountPath: /data
              name: data
          {{- if .Values.secret }}
            - mountPath: /run/secrets
              name: secrets
              secret:
                secretName: {{ include "orderly-ape.fullname" . }}
          {{- end }}
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            {{- with .Values.env }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- if not ( include "orderly-ape.hasEnvVar" (list "ALLOWED_HOSTS" .) ) }}
            - name: ALLOWED_HOSTS
              value: localhost,127.0.0.1,$(MY_POD_IP){{ if .Values.ingress.enabled }}{{ range .Values.ingress.hosts }}{{ print "," .host }}{{ end }}{{ end }}
            {{- end }}
            {{- if and .Values.ingress.enabled .Values.ingress.tls }}
            {{- if not ( include "orderly-ape.hasEnvVar" (list "CSRF_TRUSTED_ORIGINS" .) ) }}
            - name: CSRF_TRUSTED_ORIGINS
              value: http://127.0.0.1{{ range .Values.ingress.hosts }}{{ print ",https://" .host }}{{ end }}
            {{- end }}
            {{- end }}
            {{- if not ( include "orderly-ape.hasEnvVar" (list "DATABASE_URL" .) ) }}
            - name: DATABASE_URL
              value: "sqlite:////data/db.sqlite3"
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /data
              name: data
          {{- if .Values.secret }}
            - mountPath: /run/secrets
              name: secrets
              secret:
                secretName: {{ include "orderly-ape.fullname" . }}
          {{- end }}
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "orderly-ape.fullname" .) }}
          {{- else }}
          emptyDir: {}
          {{- end }}
      {{- if .Values.secret }}
        - name: secrets
          secret:
            secretName: {{ include "orderly-ape.fullname" . }}
      {{- end }}
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
