{{- if .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "orderly-ape.fullname" . }}
  labels:
    {{- include "orderly-ape.labels" . | nindent 4 }}
data:
{{- range $name, $value := .Values.secret }}
    {{ $name }}: {{ $value | b64enc }}
{{- end }}
{{- end }}
