apiVersion: v1
kind: Secret
metadata:
  name: {{ include "orderly-ape.fullname" . }}
  labels:
    {{- include "orderly-ape.labels" . | nindent 4 }}
data:
  admin-user: {{ .Values.adminUser | b64enc | quote }}
  {{- if .Values.adminPassword }}
  admin-password: {{ .Values.adminPassword | b64enc | quote }}
  {{- else }}
  admin-password: {{ include "orderly-ape.password" . }}
  {{- end }}
{{- range $name, $value := .Values.secret }}
    {{ $name }}: {{ $value | b64enc }}
{{- end }}
