---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - batch
  resources:
  - Job
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - Job/finalizers
  verbs:
  - update
- apiGroups:
  - batch
  resources:
  - Job/status
  verbs:
  - get
  - patch
  - update
