# permissions for end users to edit testruns.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k6-operator
    app.kubernetes.io/managed-by: kustomize
  name: testrun-editor-role
rules:
  - apiGroups:
      - batchv1
    resources:
      - jobs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
