# permissions for end users to view testruns.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k6-operator
    app.kubernetes.io/managed-by: kustomize
  name: testrun-viewer-role
rules:
  - apiGroups:
      - batchv1
    resources:
      - jobs
    verbs:
      - get
      - list
      - watch
