ingress:
  enabled: true
  hosts:
    - host: orderly-ape.bitpoke.cloud
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: orderly-ape-tls
      hosts:
        - orderly-ape.bitpoke.cloud
persistence:
  enabled: true
  storageClassName: standard-rwo
