# Generated by Django 5.0.6 on 2024-05-16 11:48

import django.db.models.deletion
import django.db.models.functions.datetime
import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TestLocation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        verbose_name="Updated at",
                    ),
                ),
                ("name", models.SlugField(unique=True)),
                ("display_name", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "Test Location",
                "verbose_name_plural": "Test Locations",
                "db_table": "loadtest_location",
            },
        ),
        migrations.CreateModel(
            name="TestRun",
            fields=[
                (
                    "id",
                    models.AutoField(
                        editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        verbose_name="Updated at",
                    ),
                ),
                ("name", models.SlugField(unique=True)),
                ("target", models.URLField()),
                (
                    "source_repo",
                    models.CharField(
                        default="github.com/ReviewSignal/k6-WordPress-benchmarks",
                        max_length=200,
                        verbose_name="Git repository",
                    ),
                ),
                (
                    "source_ref",
                    models.CharField(
                        default="main", max_length=200, verbose_name="Git Reference"
                    ),
                ),
                (
                    "source_script",
                    models.CharField(
                        default="loadtest.js",
                        max_length=200,
                        verbose_name="Test script file",
                    ),
                ),
            ],
            options={
                "verbose_name": "Test Run",
                "verbose_name_plural": "Test Runs",
                "db_table": "loadtest_test_run",
            },
        ),
        migrations.CreateModel(
            name="TestRunLocation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("num_workers", models.PositiveSmallIntegerField(default=1)),
                ("online_workers", models.PositiveSmallIntegerField(default=0)),
                (
                    "status",
                    django_fsm.FSMField(
                        choices=[
                            ("pending", "Pending"),
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("status_description", models.TextField(blank=True)),
                (
                    "location",
                    models.ForeignKey(
                        db_column="location",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="loadtest.testlocation",
                        to_field="name",
                    ),
                ),
                (
                    "test_run",
                    models.ForeignKey(
                        db_column="test_run",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="loadtest.testrun",
                        to_field="name",
                    ),
                ),
            ],
            options={
                "verbose_name": "Test Run Location",
                "verbose_name_plural": "Test Run Locations",
                "db_table": "loadtest_test_run_location",
                "unique_together": {("test_run", "location")},
            },
        ),
    ]
