# Generated by Django 5.0.6 on 2024-07-05 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loadtest', '0002_testrun_draft_alter_testrun_dedicated_nodes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestRunEnvVar',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.SlugField(help_text='Environment variable name', verbose_name='Name')),
                ('value', models.TextField(help_text='Environment variable value', verbose_name='Value')),
                ('test_run', models.ForeignKey(db_column='test_run', on_delete=django.db.models.deletion.CASCADE, related_name='env_vars', to='loadtest.testrun', to_field='name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestRunLabel',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.SlugField(help_text='Environment variable name', verbose_name='Name')),
                ('value', models.SlugField(help_text='Environment variable value', max_length=200, verbose_name='Value')),
                ('test_run', models.ForeignKey(db_column='test_run', on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='loadtest.testrun', to_field='name')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
