# Generated by Django 5.0.6 on 2024-07-07 23:51

import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loadtest', '0003_testrunenvvar_testrunlabel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrunenvvar',
            name='value',
            field=models.TextField(blank=True, help_text='Environment variable value', verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='testrunlocation',
            name='status',
            field=django_fsm.FSMField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('ready', 'Ready'), ('running', 'Running'), ('canceled', 'Canceled'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50),
        ),
    ]
