# Generated by Django 5.1 on 2024-09-02 11:52

import django.db.models.deletion
import django.db.models.functions.datetime
import loadtest.models
from django.db import migrations, models


def create_default_output(apps, schema_editor):
    TestOutputConfig = apps.get_model("loadtest", "TestOutputConfig")
    TestOutputConfig.objects.create(
        name="default",
        influxdb_url="http://influxdb.example.com",
        influxdb_token="",
        influxdb_org="default",
    )


class Migration(migrations.Migration):
    dependencies = [
        ("loadtest", "0004_alter_testrunenvvar_value_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestOutputConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        verbose_name="Updated at",
                    ),
                ),
                ("name", models.SlugField(unique=True)),
                ("influxdb_url", models.URLField(verbose_name="InfluxDB Server URL")),
                (
                    "influxdb_token",
                    models.CharField(max_length=200, verbose_name="InfluxDB Token"),
                ),
                (
                    "influxdb_org",
                    models.CharField(
                        default="default",
                        max_length=200,
                        verbose_name="InfluxDB Organization",
                    ),
                ),
                (
                    "influxdb_bucket",
                    models.CharField(
                        default="default",
                        max_length=200,
                        verbose_name="InfluxDB Bucket",
                    ),
                ),
                (
                    "insecure_skip_verify",
                    models.BooleanField(
                        default=False,
                        help_text="Use TLS but skip chain & host verification",
                        verbose_name="Skip TLS verification",
                    ),
                ),
            ],
            options={
                "verbose_name": "Test Output",
                "verbose_name_plural": "Test Outputs",
                "db_table": "loadtest_output",
            },
        ),
        migrations.RunPython(create_default_output),
        migrations.AddField(
            model_name="testrun",
            name="test_output",
            field=models.ForeignKey(
                db_column="test_output",
                default=loadtest.models.TestOutputConfig.default,
                help_text="Influxdb configuration for storing test results.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="loadtest.testoutputconfig",
                to_field="name",
                verbose_name="Test Output",
            ),
        ),
    ]
