# Generated by Django 5.1 on 2024-09-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loadtest', '0005_testoutputconfig_testrun_test_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='testlocation',
            name='last_ping',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Location last checkin'),
        ),
    ]
