# Generated by Django 5.1.2 on 2024-12-02 17:22
import logging

from django.contrib.auth.models import Group, Permission
from django.core.management.sql import emit_post_migrate_signal
from django.db import migrations

logger = logging.getLogger(__name__)

role_permissions = {
    "Worker": [
        "add_testlocation",
        "view_testlocation",
        "change_testrun",
        "view_testrun",
        "add_testrunlocation",
        "change_testrunlocation",
        "view_testrunlocation",
    ],
}


# See https://code.djangoproject.com/ticket/23422
def add_role_permissions(apps, schema_editor):
    emit_post_migrate_signal(2, False, "default")

    for r in role_permissions:
        role, _ = Group.objects.get_or_create(name=r)
        logger.info(f"{r} Role retrieved")
        for p in role_permissions[r]:
            perm, _ = Permission.objects.get_or_create(codename=p)
            role.permissions.add(perm)
            logger.info(f"Permitting {r} to {p}")
        role.save()


class Migration(migrations.Migration):
    dependencies = [
        (
            "loadtest",
            "0001_initial_squashed_0007_rename_testrun_start_test_at_testrun_completed_at_and_more",
        ),
        (
            "contenttypes",
            "__latest__",
        ),  # required or emit_post_migrate_signal will bail out
    ]

    operations = [
        migrations.RunPython(add_role_permissions),
    ]
