{{- if .Values.dex.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "orderly-ape.fullname" . }}-oidc-dex
  labels:
    {{- include "orderly-ape.labels" . | nindent 4 }}
data:
  OIDC_ISSUER_URL: {{ include "orderly-ape.dexIssuer" . | b64enc }}
  OIDC_CLIENT_ID: {{ include "orderly-ape.dexClientID" . | b64enc }}
  OIDC_CLIENT_SECRET: {{ include "orderly-ape.dexClientSecret" . | b64enc }}
  OIDC_REDIRECT_URL: {{ printf "%s/auth/callback" (include "orderly-ape.baseURL" .) | b64enc }}
{{- end }}
