{{- if .Values.dex.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "orderly-ape.fullname" . }}-dex-env
  labels:
    {{- include "orderly-ape.labels" . | nindent 4 }}
data:
  DEX_ISSUER: {{ include "orderly-ape.dexIssuer" . | b64enc }}
{{- end }}
