{{- if .Values.grafana.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "orderly-ape.fullname" . }}-grafana-token
  labels:
    {{- include "orderly-ape.labels" . | nindent 4 }}
{{- end }}
