apiVersion: v1
kind: Secret
metadata:
  name: {{ include "orderly-ape.fullname" . }}
  labels:
    {{- include "orderly-ape.labels" . | nindent 4 }}
data:
  private-key.pem: "{{ include "orderly-ape.rsaPrivateKey" . | b64enc }}"
{{- if .Values.jwt.rsaPublicKey }}
  public-key.pem: "{{ .Values.jwt.rsaPublicKey | b64enc }}"
{{- end }}
{{- if .Values.secret }}
{{- range $name, $value := .Values.secret }}
  {{ $name }}: {{ $value | b64enc }}
{{- end }}
{{- else if (not (hasKey .Values.secret "env")) }}
  env: ""
{{- end }}
