apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k6-operator.fullname" . }}
  labels:
    {{- include "k6-operator.labels" . | nindent 4 }}
data:
  API_ENDPOINT: {{ default "" .Values.config.api.endpoint | b64enc | quote }}
  API_USER: {{ default "" .Values.config.api.user | b64enc | quote }}
  API_PASSWORD: {{ default "" .Values.config.api.password | b64enc | quote }}
  REGION: {{ default "" .Values.config.region | b64enc | quote }}
  JOBS_NAMESPACE: {{ .Release.Namespace | b64enc | quote }}
