# grafana:
#   host: grafana.example.com
#   adminPassword: please-change-me
#
# influxdb:
#   host: influx.example.com
#   adminPassword: please-change-me
#
# orderlyape:
#   host: ape.example.com
#   adminPassword: please-change-me
#   workerBootstrapPassword: insecure-regenerate-Qxtg7kWwA5EgK7kAwe
